# Python - Sürətli Giriş

Salam. Bu dərs _Navier Stokes-a 12 Addım_ dərslərini istifadə edəbilməyiniz üçün lazımi Python proqramlaşdırmasına zəmin yaratmaq üçün giriş məqsədini güdür.  

Dərsləri Python ilə istifadə edə bilmək üçün kompyuterinizə Python yükləməli olacaqsınız. Bununla birlikdə ya conda ipython ya da jupyter yükləməlisiniz.

Terminal vasitəsi ilə kompyuterinizə yüklədiyiniz .ipynb sənədlərinin olduğu qovluğa gəldikdən sonra bu qovluqda notebook servisini başlatmalısınız. Bunun üçün terminalda aşağıdakı sətri yazmağınız kifayətdir:

jupyter-notebook (jupyter üçün)

ipython notebook (conda üçün)

Brauzerinizdə açılan yeni pəncərədə qovluqdakı _notebook_-ların listini görəcəksiniz. Hər hansı birini açaraq başlaya bilərsiniz.

## Kitabxanalar

Python açıq qaynaq (_opensource_ ) dildir. _Python dünyası_ öz daxilində matis (array) operasiyaları, diaqram funksiyaları və s. kimi paket vəya kitabxanaları cəmləşdirir. Biz bu kitabxanaları öz Python proqramımıza əlavə edərək (_import_) proqramın imkanlarını genişləndirə bilərik.  

Beləliklə, bizə kömək edə biləcək bir sıra kitabxanaları proqramımıza əlavə etməklə başlayaq. İlk növbədə, çox işimizə yarayacaq **NumPy** kitabxanasıdır. Bu kitabxana bir çox yararlı matris əməliyyatları funksiyalarını tədarük edir (MATLAB bənzəri). Növbəti kitabxana nəticələrimizi göstərmək üçün istifadə edəcəyimiz 2-ölçülü diaqram kitabxanası **Matplotlib** olacaq. 

Aşağıdakı kod sətirləri bir çox proqramınızın ilk sətirləri olacaq. Bunları çalışdırın.

In [1]:
# <-- python-da şərhlər, bu sətirdə olduğu kimi, diez işarəsi ilə başlayır.

import numpy                 # matrix kitabxabasını əlavə edirik
from matplotlib import pyplot    # diaqram kitabxanasını əlavə edirik

`numpy` kitabxanasını və `matplotlib` kitabxanasından `pyplot` modulunu əlavə edirik.
Bu kitabxanalara aid hansısa funksiyanı istifadə etmək üçün Python-a harada axtarmalı olduğunu deməliyik. Bunun üçün hər funksiyadan əvvəl aid olduğu kitabxana nöqtə ilə ayrılaraq yazılır.
Beləliklə, başlanğıcı və sonu arasında eyni fərqlə müəyyən sayda elementi olan vektor yaradan NumPy funksiyası [linspace()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.linspace.html) istifadə etmək üçün aşağıdakı sətirləri yazırıq.

In [2]:
myarray = numpy.linspace(0, 5, 10)
myarray

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

Əgər `linspace()`dən əvvəl `numpy` çağırmasaq Python xəta bildirəcək.

In [3]:
myarray = linspace(0, 5, 10)

NameError: name 'linspace' is not defined

`linspace()` funksiyası xeyli yararlıdır. Parametrləsini dəyişdirərək özünüz testlər edin.

**Import stilləri:**

Bəzi hallardan aşağıdakı sətirləri istifadə edən kodlarla qarşılaşacaqsınız
```Python
import numpy as np
import matplotlib.pyplot as plt
```
Bunlar NumPy kitabxanası bə pyplot modulu üçün 'qısa yollar'dır. Bu tipdə istifadə ilə tez-tez qarşılaşsanızda biz açıq şəkildə istifadəyə üstünlük verəcəyik. Düşünürük ki, açıq şəkildə istifadə kodun oxunaqlılığını artırır.

**Peşəkar tövsiyəsi:**

Bəzən bütün kitabxananı qısa yol istifadə edilmədən əlavə edildiyi ilə qarşılaşa bilərsiniz (məsələn: `from numpy import *`). Bu kimi istifadələr sürətli yazmağı mümkün edir, ancaq müəyyən problemlərə səbəb ola bilər. Budur ki, əvvəldən yaxşı vərdişlər etmək daha yaxşı olar.

## Dəyişkənlər

Python C və digər proqramlaşdırma dillərindəki kimi eksplisit dəyişkən bəyanına ehtiyac duymur.

In [4]:
a = 5        # a tam ədəddir (integer)
b = 'beş'   # b string-dir
c = 5.0      # c kəsr ədəddir (float) 

In [5]:
type(a)

int

In [6]:
type(b)

str

In [7]:
type(c)

float

Qeyd edək ki, integer ilə integer bölünərsə nəticə float olacaq. (Python 2.7 də *fərqli* idi. Ehiyatlı olun!)

## Python-da abzaslar

Python bəyanları qruplaşdırmaq üçün abzaslar və boşluqlardan istifadə edir. C dilində qısa bir loop aşağıdakı kimi yazılır:
```C
    for (i = 0, i < 5, i++){
       printf("Salam! \n");
    }
```

Python C dilində olduğu kimi, qıvrım mötərizlər istifadə etmir. Yuxarıda gördüyünüz kod Python-da belə yazılır:

In [8]:
for i in range(5):
    print("Salam \n")

Salam 

Salam 

Salam 

Salam 

Salam 



Əgər iç-içə for-loop yazacaqsınızsa əlavə abzaslardan istifadə edəcəksiniz.

In [9]:
for i in range(3):
    for j in range(3):
        print(i, j)
    
    print("Bu ifadə i loop-undadır, j loop-unda deyil.")

0 0
0 1
0 2
Bu ifadə i loop-undadır, j loop-unda deyil.
1 0
1 1
1 2
Bu ifadə i loop-undadır, j loop-unda deyil.
2 0
2 1
2 2
Bu ifadə i loop-undadır, j loop-unda deyil.


## Matrisləri dilimləmək

NumPy-da vektorun və ya matrisin hissələrinə `Matlab`da olduğu kimi baxa bilərsiniz. Gəlin, 1-dən 5-ə qədər elementləri olan vektora nəzər yetirək.

In [10]:
vektor1 = numpy.array([1, 2, 3, 4, 5])
vektor1

array([1, 2, 3, 4, 5])

Pythonda indeks 0-dan başlayır. `vektor1` adlandırdığımız vektorun birinci və sonuncu elementlərinə baxaq.

In [11]:
vektor1[0], vektor1[4]

(1, 5)

`vektor1` vektorunun 5 elementi var, ancaq `vektor1[5]` elementinə baxmaq istəsək Python `vektor1[5]` ilə 6-cı elementi çağırdığımız üçün xəta verəcək.

In [13]:
vektor1[5]

IndexError: index 5 is out of bounds for axis 0 with size 5

Vektor və matrislər müəyyən intervalda dilimlənə də bilər. Gəlin vektorumuzun ilk üç elementinə baxaq.

In [14]:
vektor1[0:3]

array([1, 2, 3])

Diqqət etmək lazımdır ki, dilimin aşağı həddi daxildir, yuxarı həddi isə daxil deyildir. Beləliklə yuxarıdakı kod bizə `vektor1[0]`, `vektor1[1]` və `vektor1[2]` elementlərini göstərir, ancaq `vektor1[3]` elementini göstərmir.

## Vektor Dəyişkənlərininin Təyin edilməsi

Bir çoxlarını çaşdıran Python xüsusiyyətlərindən biri vektor və ya matrislərin təyin edilməsi və elementlərinin qarşılarşdırılması ilə əlaqəlidir. Gəlin bir $a$ vektoru təyin edək:

In [17]:
a = numpy.linspace(1,5,5)

In [18]:
a

array([1., 2., 3., 4., 5.])

Beləliklə elementləri 1-dən 5-ə qədər olan bir vektor əldə etdik. Bu vektorun bir kopyasını hazırlayıb $b$ kimi adlandırmaq istəyirəmsə aşağıdakı sətirləri istifadə edəcəyəm.

In [19]:
b = a

In [20]:
b

array([1., 2., 3., 4., 5.])

Əla! İndi elemntləri 1-dən 5-ə qədər olan $a$ və $b$ vektorlarım var. Deməli əlimdə $a$ vektorunun bir nüsxəsi olduğu üçün məlumatları itirməkdən qorxmayacağam (ya da mənə elə gəlir).

In [21]:
a[2] = 17

In [22]:
a

array([ 1.,  2., 17.,  4.,  5.])

Burada, $a$ vektorunun 3-cü elementini 17 ilə əvəz etdim. İndi isə $b$ vektoruna nəzər salaq.

In [23]:
b

array([ 1.,  2., 17.,  4.,  5.])

Budur! istədiyimiz alınmadı. $a = b$ kimi ifadələr istifadə etdiyimiz zaman Python nüsxə yaratmaq əvəzinə sadəcə olaraq ləqəb (_alias_ ) yaradır və yeni yaradılan $b$ dəyişkəni əslində $a$-a işarə edir. Yəni $a$-da etdiyimiz hər bir dəyişiklik $b$-də də öz əksini tapacaq. Əgər $a$-nın həqiqi kopyasını istəyirsinizsə Python-a $a$-nın hər bir elementini ayrı-ayrı kopyalamağını tapşırmalısınız. 

In [24]:
c = a.copy()

İndi, $a$-da dəyişiklik edib $c$-bi müşəhidə edə bilərik.

In [25]:
a[2] = 3

In [26]:
a

array([1., 2., 3., 4., 5.])

In [27]:
c

array([ 1.,  2., 17.,  4.,  5.])

Alındı.

Əgər `a = b` ilə `a = b.copy()` arasındakı fərq hələ də aydın deyilsə bu hissəni qavrayana qədər yenidən oxumalısınız, çünki bu məsələ hər necəsə yenidən qarşınıza çıxacaq. 

In [28]:
from IPython.core.display import HTML
def css_styling():
    styles = open("../styles/custom.css", "r").read()
    return HTML(styles)
css_styling()